# Change these first
owner: CipherCrafts # Your GitHub organization or username, where this repository lives
repo: shadowcore-upptime # The name of this repository

sites:
  - name: Shadowcore SMP
    url: https://mc11.mc-node.net/
    port: 25630
  - name: Main Site
    url: https://shadowcoresmp.nl/
  - name: Upptime Site
    url: https://stats.shadowcoresmp.nl/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: stats.shadowcoresmp.nl
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime - Shadowcore SMP
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Hier kan je zien welke sites online zijn en of er iets fout is gegaan.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
